[Mod]
Name = "沙勒食堂附属：控制台启用器"
Version = "1.0.0"
VersionCode = 1
Author = "GlassesMita"
UniqueId = "SchaleIzakaya.ConsoleEnabler"
Description = "启用 EA Debug Console（游戏内部调试控制台）"
Link = "https://github.com/GlassesMita/SchaleIzakaya-LanguageInjector"

DepsList = []
OptionalDependencies = []
IncompatibleWith = []

IncludePDB = true

GameVersion = "1.0.0"
MinimumGameVersion = "1.0.0"
MaximumGameVersion = "2.0.0"

Tags = ["功能扩展", "游戏内容", "调试工具"]
License = "MIT"
UpdateUrl = "https://api.github.com/repos/GlassesMita/SchaleIzakaya-LanguageInjector/releases/latest"
Icon = "icon.png"

EnabledByDefault = true

[Mod.Custom]